import flet as ft
from pages.dictionary import Dictionary
from pages.students import Students
from pages.lectures import Lectures
from pages.courses import Courses
from pages.lesson import Lessons
from pages.subjects import Subjects
from pages.translator import Translator
from pages.braille import Braille
from pages.dashboard import Dashboard
from pages.gallery import Gallery
from flet import *
from flet_multi_page import subPage